;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
	abort-recursive-edit
	ace-jump-done
	ace-jump-mode
	ace-jump-move
	autopair-insert-opening
	autopair-insert-or-skip-quote
	autopair-newline
	autopair-skip-close-maybe
	c-electric-delete-forward
	c-electric-semi&comma
	ignore
	list-bookmarks
	mouse-save-then-kill
	mouse-secondary-save-then-kill
	next-buffer
	org-delete-char
	org-self-insert-command
	sgml-close-tag
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-colon
	mouse-buffer-menu
	mouse-yank-primary
	tags-loop-continue
	yas-expand
	))
